Repository TrandPick/TrendPick_Pro, pull requests merged in 2023-08, with the labels that each got.

#399 Test/398 ask
  Dockerfile
  README.md
  src/main/java/project/trendpick_pro/global/config/JpaAuditingConfig.java
  src/main/resources/application-test.yml
  src/test/java/project/trendpick_pro/ControllerTestSupport.java
  src/test/java/project/trendpick_pro/IntegrationTestSupport.java
  src/test/java/project/trendpick_pro/domain/ask/controller/AskControllerTest.java
  src/test/java/project/trendpick_pro/domain/ask/entity/AskTest.java
  src/test/java/project/trendpick_pro/domain/ask/repository/AskRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/ask/service/impl/AskServiceTest.java
Labels: feature, test

#401 Test/400 coupon
  src/main/java/project/trendpick_pro/domain/coupon/controller/CouponCardController.java
  src/main/java/project/trendpick_pro/domain/coupon/controller/CouponController.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/Coupon.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/CouponCard.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/dto/request/StoreCouponSaveRequest.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/dto/response/CouponResponse.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/expirationPeriod/ExpirationPeriod.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/expirationPeriod/ExpirationType.java
  src/main/java/project/trendpick_pro/domain/coupon/repository/CouponCardRepository.java
  src/main/java/project/trendpick_pro/domain/coupon/service/CouponCardService.java
  src/main/java/project/trendpick_pro/domain/coupon/service/CouponService.java
  src/main/resources/templates/trendpick/usr/member/join.html
  src/test/java/project/trendpick_pro/domain/coupon/controller/CouponControllerTest.java
  src/test/java/project/trendpick_pro/domain/coupon/entity/CouponCardTest.java
  src/test/java/project/trendpick_pro/domain/coupon/entity/expirationPeriod/ExpirationPeriodTest.java
  src/test/java/project/trendpick_pro/domain/coupon/entity/expirationPeriod/ExpirationTypeTest.java
  src/test/java/project/trendpick_pro/domain/coupon/repository/CouponCardRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/coupon/repository/CouponRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/coupon/service/impl/CouponServiceTest.java
Labels: refactor, test

#404 refactor: 멤버타입 이름 수정 (#402)
  src/main/java/project/trendpick_pro/domain/member/entity/MemberRoleType.java
Labels: refactor

#405 Test/402 member
  src/main/java/project/trendpick_pro/domain/coupon/controller/CouponController.java
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/dto/request/TagRequest.java
  src/main/java/project/trendpick_pro/global/util/rq/Rq.java
  src/test/java/project/trendpick_pro/ControllerTestSupport.java
  src/test/java/project/trendpick_pro/domain/ask/controller/AskControllerTest.java
  src/test/java/project/trendpick_pro/domain/coupon/controller/CouponControllerTest.java
  src/test/java/project/trendpick_pro/domain/member/controller/MemberControllerTest.java
  src/test/java/project/trendpick_pro/domain/member/entity/MemberRoleTypeTest.java
  src/test/java/project/trendpick_pro/domain/member/entity/MemberTest.java
  src/test/java/project/trendpick_pro/domain/member/repository/MemberRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/member/service/MemberServiceTest.java
Labels: refactor, test

#409 Test/408_tagTest
  src/main/java/project/trendpick_pro/domain/cart/controller/CartController.java
  src/main/java/project/trendpick_pro/domain/cart/entity/Cart.java
  src/main/java/project/trendpick_pro/domain/cart/entity/CartItem.java
  src/main/java/project/trendpick_pro/domain/cart/repository/CartItemRepository.java
  src/main/java/project/trendpick_pro/domain/cart/repository/CartRepository.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/cart/service/impl/CartServiceImpl.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/CartToOrderRequest.java
  src/main/java/project/trendpick_pro/domain/orders/service/impl/OrderServiceImpl.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/global/util/rsData/RsData.java
  src/main/resources/application-test.yml
  src/main/resources/templates/trendpick/products/detailpage.html
  src/test/java/project/trendpick_pro/domain/cart/controller/CartControllerTest.java
  src/test/java/project/trendpick_pro/domain/cart/repository/CartItemRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/cart/repository/CartRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/cart/service/impl/CartServiceImplTest.java
Labels: refactor, test

#410 Test/408_TagsTest
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/entity/FavoriteTag.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/repository/FavoriteTagRepository.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/service/impl/FavoriteTagServiceImpl.java
  src/main/java/project/trendpick_pro/domain/tags/tag/repository/TagRepository.java
  src/test/java/project/trendpick_pro/domain/cart/service/impl/CartServiceImplTest.java
  src/test/java/project/trendpick_pro/domain/tags/favoritetag/entity/FavoriteTagTest.java
  src/test/java/project/trendpick_pro/domain/tags/favoritetag/repository/FavoriteTagRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/tags/favoritetag/service/impl/FavoriteTagServiceImplTest.java
  src/test/java/project/trendpick_pro/domain/tags/tag/repository/TagRepositoryTest.java
Labels: refactor, test

#412 Test/411 orders
  src/main/java/project/trendpick_pro/domain/cart/entity/dto/response/CartResponse.java
  src/main/java/project/trendpick_pro/domain/cart/service/impl/CartServiceImpl.java
  src/main/java/project/trendpick_pro/domain/common/file/CommonFile.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/expirationPeriod/ExpirationType.java
  src/main/java/project/trendpick_pro/domain/coupon/service/impl/CouponCardServiceImpl.java
  src/main/java/project/trendpick_pro/domain/notification/entity/Notification.java
  src/main/java/project/trendpick_pro/domain/notification/entity/NotificationType.java
  src/main/java/project/trendpick_pro/domain/notification/exception/NotificationTypeNotMatchException.java
  src/main/java/project/trendpick_pro/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/CartToOrderRequest.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/OrderStateResponse.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/ProductOrderRequest.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderDetailResponse.java
  src/main/java/project/trendpick_pro/domain/orders/exception/OrderItemNotFoundException.java
  src/main/java/project/trendpick_pro/domain/orders/exception/OrderNotFoundException.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderItemRepository.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepository.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/orders/service/impl/OrderServiceImpl.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/Product.java
  src/main/java/project/trendpick_pro/domain/product/entity/productOption/ProductOption.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductOptionRepository.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/product/service/impl/ProductServiceImpl.java
  src/main/java/project/trendpick_pro/domain/rebate/controller/AdmRebateController.java
  src/main/java/project/trendpick_pro/domain/rebate/entity/RebateOrderItem.java
  src/main/java/project/trendpick_pro/domain/rebate/repository/RebateOrderItemRepository.java
  src/main/java/project/trendpick_pro/domain/rebate/service/RebateService.java
  src/main/java/project/trendpick_pro/domain/rebate/service/impl/RebateServiceImpl.java
  src/main/java/project/trendpick_pro/global/exception/ErrorCode.java
  src/main/java/project/trendpick_pro/global/exception/GlobalExceptionAdvice.java
  src/main/java/project/trendpick_pro/global/job/makeRebateData/MakeRebateDataJobConfig.java
  src/main/java/project/trendpick_pro/global/kafka/KafkaProducerService.java
  src/main/java/project/trendpick_pro/global/redis/redisson/service/RedissonService.java
  src/main/java/project/trendpick_pro/global/tosspayment/controller/PaymentController.java
  src/main/resources/templates/trendpick/admin/rebateOrderItemList.html
  src/main/resources/templates/trendpick/admin/sales.html
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
  src/test/java/project/trendpick_pro/ControllerTestSupport.java
  src/test/java/project/trendpick_pro/domain/ask/repository/AskRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/ask/service/impl/AskServiceTest.java
  src/test/java/project/trendpick_pro/domain/notification/entity/NotificationTest.java
  src/test/java/project/trendpick_pro/domain/notification/entity/NotificationTypeTest.java
  src/test/java/project/trendpick_pro/domain/orders/contoller/OrderControllerTest.java
  src/test/java/project/trendpick_pro/domain/orders/entity/OrderItemTest.java
  src/test/java/project/trendpick_pro/domain/orders/entity/OrderTest.java
  src/test/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryTest.java
  src/test/java/project/trendpick_pro/learning/reddison/RedissonLearningTest.java
Labels: refactor, test

#414 refactor: 배포환경에 맞춘 변수 변경 (#383)
  src/main/java/project/trendpick_pro/global/config/RedissonConfig.java
  src/main/resources/templates/trendpick/orders/order-form.html
Labels: refactor

#416 배포환경에 맞는 환경변수 부여 (#415)
  src/main/java/project/trendpick_pro/global/config/KafkaConfig.java
  src/main/java/project/trendpick_pro/global/config/RedissonConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
Labels: documentation, refactor

#417 배포 환경에 맞게 환경 변수 명을 수정한다.
  src/main/resources/application-test.yml
Labels: documentation, refactor

#418 refactor: 더미데이터 개수 추가
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
Labels: refactor

#430 bug: 재고 중복감소 로직 제거 (#429)
  src/main/java/project/trendpick_pro/domain/orders/service/impl/OrderServiceImpl.java
Labels: bug

#432 Fix/431 rebate and withdraw refactoring
  .gitignore
  src/main/java/project/trendpick_pro/domain/cash/entity/CashLog.java
  src/main/java/project/trendpick_pro/domain/cash/entity/dto/CashResponse.java
  src/main/java/project/trendpick_pro/domain/cash/service/CashService.java
  src/main/java/project/trendpick_pro/domain/cash/service/impl/CashServiceImpl.java
  src/main/java/project/trendpick_pro/domain/coupon/service/impl/CouponCardServiceImpl.java
  src/main/java/project/trendpick_pro/domain/delivery/entity/Delivery.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/service/impl/OrderServiceImpl.java
  src/main/java/project/trendpick_pro/domain/rebate/controller/AdmRebateController.java
  src/main/java/project/trendpick_pro/domain/rebate/entity/RebateOrderItem.java
  src/main/java/project/trendpick_pro/domain/rebate/service/RebateService.java
  src/main/java/project/trendpick_pro/domain/rebate/service/impl/RebateServiceImpl.java
  src/main/java/project/trendpick_pro/domain/store/entity/Store.java
  src/main/java/project/trendpick_pro/domain/store/service/StoreService.java
  src/main/java/project/trendpick_pro/domain/store/service/impl/StoreServiceImpl.java
  src/main/java/project/trendpick_pro/domain/withdraw/controller/AdmWithdrawController.java
  src/main/java/project/trendpick_pro/domain/withdraw/controller/WithdrawController.java
  src/main/java/project/trendpick_pro/domain/withdraw/entity/WithdrawApply.java
  src/main/java/project/trendpick_pro/domain/withdraw/service/WithdrawService.java
  src/main/java/project/trendpick_pro/domain/withdraw/service/impl/WithdrawServiceImpl.java
  src/main/java/project/trendpick_pro/global/util/rq/Rq.java
  src/main/resources/templates/trendpick/admin/rebateOrderItemList.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
Labels: bug, refactor

#433 Test/426_withdrawTest
  src/main/java/project/trendpick_pro/domain/withdraw/controller/AdmWithdrawController.java
  src/main/java/project/trendpick_pro/domain/withdraw/controller/WithdrawController.java
  src/main/java/project/trendpick_pro/domain/withdraw/entity/dto/WithDrawApplyForm.java
  src/main/java/project/trendpick_pro/domain/withdraw/repository/WithdrawApplyRepository.java
  src/main/java/project/trendpick_pro/domain/withdraw/service/WithdrawService.java
  src/main/java/project/trendpick_pro/domain/withdraw/service/impl/WithdrawServiceImpl.java
  src/test/java/project/trendpick_pro/domain/cart/controller/CartControllerTest.java
  src/test/java/project/trendpick_pro/domain/cart/repository/CartItemRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/cart/repository/CartRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/withdraw/controller/WithdrawControllerTest.java
  src/test/java/project/trendpick_pro/domain/withdraw/repository/WithdrawApplyRepositoryTest.java
  src/test/java/project/trendpick_pro/domain/withdraw/service/impl/WithdrawServiceImplTest.java
Labels: refactor, test

#435 Fix/434 fix cart
  src/main/java/project/trendpick_pro/domain/cart/entity/CartItem.java
  src/main/java/project/trendpick_pro/domain/cart/service/impl/CartServiceImpl.java
  src/main/resources/templates/trendpick/usr/layout/layout.html
Labels: bug

#440 Refactor/439 정산 프로세스 오류 수정 및 개편
  src/main/java/project/trendpick_pro/domain/brand/service/BrandService.java
  src/main/java/project/trendpick_pro/domain/brand/service/impl/BrandServiceImpl.java
  src/main/java/project/trendpick_pro/domain/cash/entity/CashLog.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/CouponCard.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/rebate/controller/AdmRebateController.java
  src/main/java/project/trendpick_pro/domain/rebate/entity/MonthRebateData.java
  src/main/java/project/trendpick_pro/domain/rebate/entity/RebateOrderItem.java
  src/main/java/project/trendpick_pro/domain/rebate/repository/MonthRebateDataRepository.java
  src/main/java/project/trendpick_pro/domain/rebate/scheduler/RebateScheduler.java
  src/main/java/project/trendpick_pro/domain/rebate/service/RebateService.java
  src/main/java/project/trendpick_pro/domain/rebate/service/impl/RebateServiceImpl.java
  src/main/java/project/trendpick_pro/domain/store/entity/Store.java
  src/main/java/project/trendpick_pro/domain/store/service/StoreService.java
  src/main/java/project/trendpick_pro/domain/store/service/impl/StoreServiceImpl.java
  src/main/java/project/trendpick_pro/domain/withdraw/entity/WithdrawApply.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/resources/templates/trendpick/admin/rebateOrderItemList.html
  src/main/resources/templates/trendpick/admin/sales.html
  src/main/resources/templates/trendpick/orders/order-form.html
Labels: bug, refactor
