Repository TrandPick/TrendPick_Pro, pull requests merged in 2023-07, with the labels that each got.

#335 Feat/300_RecommendProcessWithSpringBatch
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/member/repository/MemberRepository.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepository.java
  src/main/java/project/trendpick_pro/domain/recommend/controller/RecommendController.java
  src/main/java/project/trendpick_pro/domain/recommend/repository/JdbcRecommendRepository.java
  src/main/java/project/trendpick_pro/domain/recommend/repository/RecommendRepository.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/global/job/JobConfig.java
  src/main/java/project/trendpick_pro/global/job/JobController.java
  src/main/java/project/trendpick_pro/global/job/cancelOrderJobConfig/CancelOrderJobConfig.java
  src/main/java/project/trendpick_pro/global/job/makeRecommendProductJobConfig/MakeRecommendProductJobConfig.java
  src/main/resources/templates/trendpick/products/coupons.html
Labels: feature, refactor

#337 [#336] 부하테스트를 위한 DB 연결정보 변경
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
Labels: feature

#338 docs: DB 아이디,비밀번호 변경 (#336)
  src/main/resources/application-prod.yml
Labels: bug

#343 [#342] Refactor/342 yml env
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/templates/trendpick/products/detailpage.html
Labels: refactor

#349 [#348] 부하테스트 후 코드 개선
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/ProductStatus.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/request/ProductSearchCond.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductListResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/productOption/ProductOption.java
  src/main/java/project/trendpick_pro/domain/product/entity/productOption/dto/ProductOptionSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/jmeter/JmeterController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-ela.yml
  src/main/resources/templates/trendpick/orders/standByOrder.html
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/products/modify.html
Labels: refactor

#350 트랜드픽 배포
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/member/repository/MemberRepository.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/ProductStatus.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/request/ProductSearchCond.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductListResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/productOption/ProductOption.java
  src/main/java/project/trendpick_pro/domain/product/entity/productOption/dto/ProductOptionSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/rebate/controller/AdmRebateController.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/domain/withdraw/controller/AdmWithdrawController.java
  src/main/java/project/trendpick_pro/domain/withdraw/controller/WithdrawController.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/jmeter/JmeterController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-ela.yml
  src/main/resources/templates/trendpick/admin/withDrawList.html
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/orders/standByOrder.html
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/products/modify.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
Labels: refactor

#356 feat: 누적 접속자 파악을 위한 로직 추가 (#355)
  src/main/java/project/trendpick_pro/domain/common/view/entity/View.java
  src/main/java/project/trendpick_pro/domain/common/view/repository/ViewRepository.java
  src/main/java/project/trendpick_pro/domain/common/view/service/ViewService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/config/RedisConfig.java
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/products/list.html
Labels: feature

#357 트랜드픽 배포
  src/main/java/project/trendpick_pro/domain/common/view/entity/View.java
  src/main/java/project/trendpick_pro/domain/common/view/repository/ViewRepository.java
  src/main/java/project/trendpick_pro/domain/common/view/service/ViewService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/config/RedisConfig.java
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/products/list.html
Labels: feature

#361 Refactor/353_RefactorCode
  src/main/java/project/trendpick_pro/domain/brand/service/BrandService.java
  src/main/java/project/trendpick_pro/domain/brand/service/BrandServiceImpl.java
  src/main/java/project/trendpick_pro/domain/cart/entity/dto/request/CartRequest.java
  src/main/java/project/trendpick_pro/domain/cart/repository/CartItemRepository.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartServiceImpl.java
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/coupon/service/CouponService.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/store/entity/Store.java
  src/main/java/project/trendpick_pro/domain/store/repository/StoreRepository.java
  src/main/java/project/trendpick_pro/domain/store/service/StoreService.java
  src/main/java/project/trendpick_pro/domain/store/service/StoreServiceImpl.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/entity/FavoriteTag.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/service/FavoriteTagService.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/service/FavoriteTagServiceImpl.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/dto/response/TagListResponse.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/dto/response/TagResponse.java
  src/main/java/project/trendpick_pro/domain/tags/tag/service/TagService.java
  src/main/java/project/trendpick_pro/domain/tags/tag/service/TagServiceImpl.java
  src/main/java/project/trendpick_pro/domain/tags/type/TagType.java
  src/main/java/project/trendpick_pro/domain/withdraw/controller/WithdrawController.java
  src/main/java/project/trendpick_pro/domain/withdraw/repository/WithdrawApplyRepository.java
  src/main/java/project/trendpick_pro/domain/withdraw/service/WithdrawService.java
  src/main/java/project/trendpick_pro/domain/withdraw/service/WithdrawServiceImpl.java
  src/main/java/project/trendpick_pro/global/job/JobTestController.java
  src/main/java/project/trendpick_pro/global/tosspayment/controller/PaymentController.java
Labels: refactor

#368 docs: 서버 구성 update로 변경 (#367)
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/resources/application-prod.yml
Labels: documentation

#370 DockerFile MultiStage Build 적용
  Dockerfile
Labels: refactor

#371 dockerfile, work.yml 수정
  .github/workflows/work-2.yml
  Dockerfile
Labels: bug

#375 쿠폰발급 페이지 오류 수정
  src/main/java/project/trendpick_pro/TrendPickProApplication.java
  src/main/java/project/trendpick_pro/domain/coupon/controller/CouponController.java
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductServiceImpl.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendServiceImpl.java
  src/main/java/project/trendpick_pro/domain/store/entity/Store.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/store/coupon/generate.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
  src/main/resources/templates/trendpick/usr/member/info.html
Labels: bug

#377 Feat/376 jmeter order
  build.gradle
  src/main/java/project/trendpick_pro/domain/orders/service/OrderServiceImpl.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductServiceImpl.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/service/FavoriteTagServiceImpl.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/jmeter/JmeterController.java
  src/main/java/project/trendpick_pro/global/search/controller/SearchController.java
  src/main/java/project/trendpick_pro/global/search/entity/ProductSearch.java
  src/main/java/project/trendpick_pro/global/search/repository/ProductSearchRepository.java
  src/main/java/project/trendpick_pro/global/search/service/SearchService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-ela.yml
  src/main/resources/application.yml
Labels: documentation, feature, refactor

#388 트랜트픽 배포v1.1.4
  README.md
  src/main/resources/templates/trendpick/orders/order-form.html
Labels: bug, documentation

#389 트랜드픽 배포v1.1.5
  src/main/java/project/trendpick_pro/global/kafka/KafkaConsumerService.java
  src/main/java/project/trendpick_pro/global/kafka/view/service/ViewService.java
Labels: refactor

#390 Refactor/380_AddCaching
  src/main/java/project/trendpick_pro/domain/ask/entity/dto/response/AskResponse.java
  src/main/java/project/trendpick_pro/domain/ask/service/impl/AskServiceImpl.java
  src/main/java/project/trendpick_pro/domain/category/service/impl/SubCategoryServiceImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/product/service/impl/ProductServiceImpl.java
  src/main/java/project/trendpick_pro/domain/review/entity/dto/response/ReviewProductResponse.java
  src/main/java/project/trendpick_pro/domain/review/service/impl/ReviewServiceImpl.java
  src/main/resources/templates/trendpick/products/list.html
Labels: refactor

#391 트랜드픽 배포v1.1.6
  src/main/java/project/trendpick_pro/TrendPickProApplication.java
  src/main/java/project/trendpick_pro/domain/ask/entity/dto/response/AskResponse.java
  src/main/java/project/trendpick_pro/domain/ask/service/impl/AskServiceImpl.java
  src/main/java/project/trendpick_pro/domain/category/service/impl/SubCategoryServiceImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/product/service/impl/ProductServiceImpl.java
  src/main/java/project/trendpick_pro/domain/review/entity/dto/response/ReviewProductResponse.java
  src/main/java/project/trendpick_pro/domain/review/service/impl/ReviewServiceImpl.java
  src/main/resources/templates/trendpick/products/list.html
Labels: refactor

#392 Update README.md
  README.md
Labels: documentation

#394 Refactor/393 kafka one partition
  src/main/java/project/trendpick_pro/domain/category/service/impl/SubCategoryServiceImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/impl/ProductServiceImpl.java
  src/main/java/project/trendpick_pro/global/config/KafkaConfig.java
  src/main/java/project/trendpick_pro/global/jmeter/JmeterController.java
Labels: refactor

#396 Refactor/395 kafka multi pattern
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/orders/service/impl/OrderServiceImpl.java
  src/main/java/project/trendpick_pro/global/config/KafkaConfig.java
  src/main/java/project/trendpick_pro/global/jmeter/JmeterController.java
  src/main/java/project/trendpick_pro/global/kafka/KafkaConsumerService.java
  src/main/java/project/trendpick_pro/global/kafka/KafkaProducerService.java
  src/main/java/project/trendpick_pro/global/kafka/kafkasave/entity/OutboxMessage.java
  src/main/java/project/trendpick_pro/global/kafka/kafkasave/repository/OutboxMessageRepository.java
  src/main/java/project/trendpick_pro/global/kafka/kafkasave/service/OutboxMessageService.java
  src/main/resources/application.yml
Labels: feature, refactor
