Repository TrandPick/TrendPick_Pro, pull requests merged in 2023-06, with the labels that each got.

#84 refactor: 동시성 테스트 코드 구현 (#77)
  src/main/java/project/trendpick_pro/domain/cart/entity/Cart.java
  src/main/java/project/trendpick_pro/domain/cart/repository/CartRepository.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/delivery/service/DeliveryService.java
  src/main/java/project/trendpick_pro/domain/member/exception/MemberAlreadyExistException.java
  src/main/java/project/trendpick_pro/domain/member/exception/MemberNotFoundException.java
  src/main/java/project/trendpick_pro/domain/member/exception/MemberNotMatchException.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/OrderSaveRequest.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/entity/Product.java
  src/main/java/project/trendpick_pro/domain/product/exception/ProductNotFoundException.java
  src/main/java/project/trendpick_pro/domain/product/exception/ProductStockOutException.java
  src/main/java/project/trendpick_pro/global/exception/BaseException.java
  src/main/java/project/trendpick_pro/global/exception/ErrorCode.java
  src/main/java/project/trendpick_pro/global/exception/GlobalExceptionAdvice.java
  src/test/java/project/trendpick_pro/domain/orders/service/OrderServiceTest.java
Labels: refactor

#90 feat: 초기 선호태그 추가, 회원가입시에 멤버에게 선택한 선태그 저장 (#89)
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/member/entity/form/JoinForm.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/tag/entity/dto/request/TagRequest.java
  src/main/java/project/trendpick_pro/domain/tag/entity/dto/response/TagListResponse.java
  src/main/java/project/trendpick_pro/domain/tag/entity/dto/response/TagResponse.java
  src/main/java/project/trendpick_pro/domain/tag/repository/TagRepository.java
  src/main/java/project/trendpick_pro/domain/tag/service/TagService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/resources/application-tag.yml
  src/main/resources/application.yml
Labels: feature, refactor

#92 Feat/86 tagScoreIncreaseByOrder2
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/tag/entity/Tag.java
Labels: feature

#94 feat: 회원가입시에 선호태그 리스트 표시 (#91)
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/tag/entity/dto/response/TagListResponse.java
  src/main/java/project/trendpick_pro/domain/tag/service/TagService.java
Labels: feature

#96 Feat/95_tagScoreIncrease
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/tag/entity/Tag.java
  src/main/java/project/trendpick_pro/domain/tag/service/TagService.java
Labels: feature, refactor

#102 Feat/98_recomendAlgorithm
  src/main/java/project/trendpick_pro/TrendPickProApplication.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/Product.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductByRecommended.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/domain/tag/entity/Tag.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
Labels: feature, refactor

#105 Refactor/104 refactor recommend
  build.gradle
  src/main/java/project/trendpick_pro/domain/FavoriteTag.java
  src/main/java/project/trendpick_pro/domain/brand/entity/Brand.java
  src/main/java/project/trendpick_pro/domain/brand/entity/dto/BrandResponse.java
  src/main/java/project/trendpick_pro/domain/brand/repository/BrandRepository.java
  src/main/java/project/trendpick_pro/domain/brand/service/BrandService.java
  src/main/java/project/trendpick_pro/domain/category/entity/MainCategory.java
  src/main/java/project/trendpick_pro/domain/category/entity/SubCategory.java
  src/main/java/project/trendpick_pro/domain/category/entity/dto/request/CategorySaveRequest.java
  src/main/java/project/trendpick_pro/domain/category/entity/dto/response/MainCategoryResponse.java
  src/main/java/project/trendpick_pro/domain/category/entity/dto/response/SubCategoryResponse.java
  src/main/java/project/trendpick_pro/domain/category/repository/MainCategoryRepository.java
  src/main/java/project/trendpick_pro/domain/category/repository/SubCategoryRepository.java
  src/main/java/project/trendpick_pro/domain/category/service/MainCategoryService.java
  src/main/java/project/trendpick_pro/domain/category/service/SubCategoryService.java
  src/main/java/project/trendpick_pro/domain/favoritetag/repository/FavoriteTagRepository.java
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/member/entity/form/JoinForm.java
  src/main/java/project/trendpick_pro/domain/member/exception/MemberNotMatchException.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/Product.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/request/ProductSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductListResponse.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/recommend/controller/RecommendController.java
  src/main/java/project/trendpick_pro/domain/recommend/entity/dto/RecommendResponse.java
  src/main/java/project/trendpick_pro/domain/recommend/repository/RecommendRepository.java
  src/main/java/project/trendpick_pro/domain/recommend/repository/RecommendRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/recommend/repository/RecommendRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/domain/tag/entity/Tag.java
  src/main/java/project/trendpick_pro/domain/tag/service/TagService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/exception/GlobalExceptionAdvice.java
  src/main/java/project/trendpick_pro/global/security/SecurityConfig.java
  src/main/resources/application-data.yml
  src/main/resources/application-tag.yml
  src/main/resources/application.yml
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/products/register.html
  src/main/resources/templates/trendpick/usr/member/join.html
Labels: feature, refactor

#110 Feat/106_RefactorRecommend
  src/main/java/project/trendpick_pro/domain/answer/controller/AnswerController.java
  src/main/java/project/trendpick_pro/domain/cart/entity/CartItem.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/favoritetag/repository/FavoriteTagRepository.java
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/Product.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductResponse.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/recommend/controller/RecommendController.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/domain/review/controller/ReviewController.java
  src/main/java/project/trendpick_pro/domain/review/entity/Review.java
  src/main/java/project/trendpick_pro/domain/review/entity/dto/response/ReviewResponse.java
  src/main/java/project/trendpick_pro/domain/review/service/ReviewService.java
  src/main/java/project/trendpick_pro/domain/tag/service/TagService.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/entity/FavoriteTag.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/repository/FavoriteTagRepository.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/service/FavoriteTagService.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/Tag.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/dto/request/TagRequest.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/dto/response/TagListResponse.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/dto/response/TagResponse.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/type/TagType.java
  src/main/java/project/trendpick_pro/domain/tags/tag/repository/TagRepository.java
  src/main/java/project/trendpick_pro/domain/tags/tag/service/TagService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
Labels: feature, refactor

#117 feat: 기본데이터 추가 (#116)
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/basedata/tagname/entity/TagName.java
  src/main/java/project/trendpick_pro/global/basedata/tagname/entity/dto/TagNameResponse.java
  src/main/java/project/trendpick_pro/global/basedata/tagname/repository/TagNameRepository.java
  src/main/java/project/trendpick_pro/global/basedata/tagname/service/TagNameService.java
  src/main/resources/application-data.yml
Labels: feature

#119 refactor: 상품 등록 폼 개선 (#118)
  src/main/java/project/trendpick_pro/domain/brand/service/BrandService.java
  src/main/java/project/trendpick_pro/domain/category/repository/SubCategoryRepository.java
  src/main/java/project/trendpick_pro/domain/category/service/SubCategoryService.java
  src/main/java/project/trendpick_pro/domain/common/base/filetranslator/FileTranslator.java
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/Product.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/request/ProductSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductResponse.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/domain/review/service/ReviewService.java
  src/main/java/project/trendpick_pro/global/exception/GlobalExceptionAdvice.java
  src/main/java/project/trendpick_pro/global/security/SecurityConfig.java
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/products/register.html
  src/main/resources/templates/trendpick/usr/member/join.html
Labels: refactor

#120 Feat/112_OrderFormFrontEnd
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/delivery/entity/Delivery.java
  src/main/java/project/trendpick_pro/domain/member/entity/dto/MemberInfoDto.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/OrderForm.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderItemDto.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/resources/templates/trendpick/orders/order.html
Labels: feature

#123 refactor: 기본 멤버 추가(관리자)
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/resources/templates/trendpick/products/list.html
Labels: refactor

#124 Feat/121_OrderListFront
  src/main/java/project/trendpick_pro/domain/common/controller/CommonController.java
  src/main/java/project/trendpick_pro/domain/member/entity/dto/MemberInfoDto.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderStatus.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/OrderSearchCond.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderItemDto.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderResponse.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepository.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/basedata/tagname/service/TagNameService.java
  src/main/resources/templates/trendpick/orders/list.html
  src/main/resources/templates/trendpick/orders/order.html
  src/main/resources/templates/trendpick/usr/member/orders.html
Labels: feature, refactor

#126 Feat/125_AddReviewButton
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderResponse.java
  src/main/resources/templates/trendpick/usr/member/orders.html
Labels: feature

#138 Feat/136_MakeOrderpPocess
  src/main/java/project/trendpick_pro/domain/cart/controller/CartController.java
  src/main/java/project/trendpick_pro/domain/cart/entity/dto/request/CartItemRequest.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/member/entity/dto/MemberInfoDto.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/OrderRequest.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderItemDto.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/ProductOption.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/request/ProductOptionSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductOptionResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/form/ProductOptionForm.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductOptionRepository.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/usr/cart/list.html
Labels: feature, refactor

#151 feat: 상품 상세페이지, 카테고리 동적 표시 화면 추가 (#150)
  src/main/java/project/trendpick_pro/domain/cart/controller/CartController.java
  src/main/java/project/trendpick_pro/domain/cart/entity/dto/request/CartItemRequest.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/category/controller/SubCategoryController.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/request/ProductSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductResponse.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/recommend/controller/RecommendController.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/products/register.html
Labels: feature

#157 refactor: 관리자페이지에서 수정 삭제버튼 표시 (#156)
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/resources/application.yml
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/products/register.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
Labels: refactor

#161 Feat/160 toss and product
  src/main/java/project/trendpick_pro/domain/brand/service/BrandService.java
  src/main/java/project/trendpick_pro/global/security/SecurityConfig.java
  src/main/java/project/trendpick_pro/global/tosspayment/PaymentController.java
  src/main/resources/static/bulma.min.css
  src/main/resources/static/index.html
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/products/register.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
  src/main/resources/templates/trendpick/usr/member/join.html
Labels: feature, refactor

#163 refactor: 상품 상세페이지 로직 개선 (#162)
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/products/detailpage.html
Labels: refactor

#169 refactor: 로그인시 권한 확인 방법 변경 (#168)
  src/main/java/project/trendpick_pro/global/security/UserSecurityService.java
Labels: refactor

#174 Feat/173 member msg create
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/member/entity/dto/MemberInfoDto.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/OrderForm.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderItemDto.java
  src/main/java/project/trendpick_pro/global/security/SecurityConfig.java
  src/main/java/project/trendpick_pro/global/tosspayment/PaymentController.java
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/error/404.html
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
  src/main/resources/templates/trendpick/usr/member/join.html
  src/main/resources/templates/trendpick/usr/member/login.html
Labels: feature

#183 Refactor/181_RefactorRsData
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
Labels: feature, refactor

#188 Feat/185_ConnectAskList
  src/main/java/project/trendpick_pro/domain/ask/controller/AskController.java
  src/main/java/project/trendpick_pro/domain/ask/entity/dto/response/AskResponse.java
  src/main/java/project/trendpick_pro/domain/ask/repository/AskRepository.java
  src/main/java/project/trendpick_pro/domain/ask/repository/AskRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/ask/repository/AskRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/ask/service/AskService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/resources/templates/trendpick/admin/products.html
  src/main/resources/templates/trendpick/customerservice/asks/register.html
  src/main/resources/templates/trendpick/products/detailpage.html
Labels: feature

#198 Fix/장바구니에서 주문 성공시 해당 장바구니에 담긴 상품 삭제가 안되는 이슈
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderItemDto.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/resources/templates/trendpick/orders/order-form.html
Labels: bug, refactor

#200 Refactor/199 local
  src/main/java/project/trendpick_pro/domain/brand/service/BrandService.java
  src/main/java/project/trendpick_pro/domain/category/service/MainCategoryService.java
  src/main/java/project/trendpick_pro/domain/category/service/SubCategoryService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/review/controller/ReviewController.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/resources/application-data.yml
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/products/register.html
  src/main/resources/templates/trendpick/review/detail.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
  src/main/resources/templates/trendpick/usr/member/info.html
  src/main/resources/templates/trendpick/usr/member/join.html
Labels: refactor

#205 Refactor/204 sever 머지하시면 안됩니다. 배포환경 이에요!!!
  README.md
  build.gradle
  src/main/java/project/trendpick_pro/domain/common/base/filetranslator/FileTranslator.java
  src/main/java/project/trendpick_pro/domain/common/controller/CommonController.java
  src/main/java/project/trendpick_pro/domain/common/file/CommonFile.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/review/service/ReviewService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/basedata/tagname/service/TagNameService.java
  src/main/java/project/trendpick_pro/global/config/NcpS3Config.java
  src/main/resources/application-prod.yml
  src/main/resources/templates/trendpick/admin/products.html
  src/main/resources/templates/trendpick/admin/sales.html
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/products/modify.html
  src/main/resources/templates/trendpick/review/detail.html
  src/main/resources/templates/trendpick/review/list.html
  src/main/resources/templates/trendpick/usr/cart/list.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
  src/main/resources/templates/trendpick/usr/member/orders.html
Labels: refactor

#208 Refactor/207 enable redis
  build.gradle
  src/main/java/project/trendpick_pro/TrendPickProApplication.java
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: refactor

#215 트렌드픽 배포 v1.0.3
  src/main/java/project/trendpick_pro/global/config/NcpS3Config.java
Labels: refactor

#219 refactor: 기본 데이터 축소
  src/main/java/project/trendpick_pro/domain/common/base/filetranslator/FileTranslator.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
Labels: refactor

#221 refactor: 로직 개선점 추가
  src/main/java/project/trendpick_pro/domain/answer/controller/AnswerController.java
Labels: refactor

#230 트렌드픽 배포 ver1.0.4
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
Labels: refactor

#244 트렌드픽 배포 v1.1.0
  src/main/java/project/trendpick_pro/domain/answer/service/AnswerService.java
  src/main/java/project/trendpick_pro/domain/ask/entity/dto/response/AskResponse.java
  src/main/java/project/trendpick_pro/domain/ask/repository/AskRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/cart/controller/CartController.java
  src/main/java/project/trendpick_pro/domain/cart/entity/CartItem.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/delivery/entity/Delivery.java
  src/main/java/project/trendpick_pro/domain/delivery/entity/DeliveryState.java
  src/main/java/project/trendpick_pro/domain/member/controller/MemberController.java
  src/main/java/project/trendpick_pro/domain/member/service/MemberService.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderStatus.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/request/OrderSearchCond.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderDetailResponse.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderItemDto.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderResponse.java
  src/main/java/project/trendpick_pro/domain/orders/exceoption/OrderNotFoundException.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/entity/Product.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductListResponseBySeller.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/recommend/entity/Recommend.java
  src/main/java/project/trendpick_pro/domain/review/controller/ReviewController.java
  src/main/java/project/trendpick_pro/domain/review/service/ReviewService.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/repository/FavoriteTagRepository.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/service/FavoriteTagService.java
  src/main/java/project/trendpick_pro/domain/tags/tag/repository/TagRepository.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/exception/ErrorCode.java
  src/main/java/project/trendpick_pro/global/jmeter/JmeterController.java
  src/main/java/project/trendpick_pro/global/tosspayment/PaymentController.java
  src/main/java/project/trendpick_pro/global/tosspayment/PaymentService.java
  src/main/java/project/trendpick_pro/global/tosspayment/controller/PaymentController.java
  src/main/java/project/trendpick_pro/global/tosspayment/dto/PaymentCardResponse.java
  src/main/java/project/trendpick_pro/global/tosspayment/dto/PaymentResultResponse.java
  src/main/java/project/trendpick_pro/global/tosspayment/service/PaymentService.java
  src/main/resources/application-prod.yml
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/error/404.html
  src/main/resources/templates/trendpick/customerservice/asks/detail.html
  src/main/resources/templates/trendpick/orders/detail.html
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/review/detail.html
  src/main/resources/templates/trendpick/review/list.html
  src/main/resources/templates/trendpick/usr/cart/list.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
  src/main/resources/templates/trendpick/usr/member/orders.html
  src/main/resources/templates/trendpick/usr/member/refunds.html
Labels: feature

#254 Feature/253 file size
  src/main/java/project/trendpick_pro/global/exception/GlobalExceptionAdvice.java
  src/main/resources/application.yml
  src/main/resources/templates/trendpick/products/register.html
Labels: feature

#263 Feat/260_getCoupon
  src/main/java/project/trendpick_pro/domain/coupon/controller/CouponCardController.java
  src/main/java/project/trendpick_pro/domain/coupon/controller/CouponController.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/Coupon.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/CouponCard.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/CouponStorage.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/dto/request/StoreCouponSaveRequest.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/dto/response/SimpleCouponResponse.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/expirationPeriod/ExpirationPeriod.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/expirationPeriod/ExpirationType.java
  src/main/java/project/trendpick_pro/domain/coupon/repository/CouponCardRepository.java
  src/main/java/project/trendpick_pro/domain/coupon/service/CouponCardService.java
  src/main/java/project/trendpick_pro/domain/coupon/service/CouponService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/resources/templates/trendpick/coupons/list.html
  src/main/resources/templates/trendpick/store/coupon/generate.html
  src/main/resources/templates/trendpick/store/coupon/issue.html
  src/main/resources/templates/trendpick/store/coupon/list.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
Labels: feature, refactor

#267 [#259] 엘라스틱 서치를 도입하여 검색기능을 구현한다.
  build.gradle
  src/main/java/project/trendpick_pro/domain/category/entity/SubCategory.java
  src/main/java/project/trendpick_pro/domain/member/entity/Member.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/request/ProductSearchCond.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductListResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/response/ProductResponse.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/config/ElasticSearchConfig.java
  src/main/java/project/trendpick_pro/global/exception/ErrorCode.java
  src/main/java/project/trendpick_pro/global/search/controller/SearchController.java
  src/main/java/project/trendpick_pro/global/search/entity/ProductSearch.java
  src/main/java/project/trendpick_pro/global/search/exception/DocumentNotFoundException.java
  src/main/java/project/trendpick_pro/global/search/repository/ProductSearchRepository.java
  src/main/java/project/trendpick_pro/global/search/service/SearchService.java
  src/main/resources/application-data.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-ela.yml
  src/main/resources/application.yml
  src/main/resources/templates/trendpick/orders/detail.html
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/products/modify.html
  src/main/resources/templates/trendpick/products/register.html
  src/main/resources/templates/trendpick/usr/cart/list.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
  src/main/resources/templates/trendpick/usr/notification/list.html
Labels: feature

#270 [#269] 상품 옵션 로직을 추가한다.
  src/main/java/project/trendpick_pro/domain/ask/entity/Ask.java
  src/main/java/project/trendpick_pro/domain/ask/entity/dto/response/AskResponse.java
  src/main/java/project/trendpick_pro/domain/ask/repository/AskRepository.java
  src/main/java/project/trendpick_pro/domain/ask/repository/AskRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/ask/service/AskService.java
  src/main/java/project/trendpick_pro/domain/cart/entity/CartItem.java
  src/main/java/project/trendpick_pro/domain/cart/entity/dto/request/CartItemRequest.java
  src/main/java/project/trendpick_pro/domain/cart/service/CartService.java
  src/main/java/project/trendpick_pro/domain/common/base/rq/Rq.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderItemDto.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderResponse.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/ProductRequest.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/request/ProductSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/entity/form/ProductOptionForm.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/Product.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/request/ProductSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/request/ProductSearchCond.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductByRecommended.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductDiscountResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductListResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductListResponseBySeller.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/dto/response/ProductResponse.java
  src/main/java/project/trendpick_pro/domain/product/entity/productOption/ProductOption.java
  src/main/java/project/trendpick_pro/domain/product/entity/productOption/dto/ProductOptionSaveRequest.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepository.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/domain/recommend/entity/Recommend.java
  src/main/java/project/trendpick_pro/domain/recommend/repository/RecommendRepositoryCustom.java
  src/main/java/project/trendpick_pro/domain/recommend/repository/RecommendRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/recommend/service/RecommendService.java
  src/main/java/project/trendpick_pro/domain/review/entity/Review.java
  src/main/java/project/trendpick_pro/domain/review/service/ReviewService.java
  src/main/java/project/trendpick_pro/domain/tags/favoritetag/service/FavoriteTagService.java
  src/main/java/project/trendpick_pro/domain/tags/tag/entity/Tag.java
  src/main/java/project/trendpick_pro/domain/tags/tag/repository/TagRepository.java
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
  src/main/java/project/trendpick_pro/global/jmeter/JmeterController.java
  src/main/java/project/trendpick_pro/global/search/controller/SearchController.java
  src/main/java/project/trendpick_pro/global/search/entity/ProductSearch.java
  src/main/java/project/trendpick_pro/global/search/service/SearchService.java
  src/main/resources/application-data.yml
  src/main/resources/templates/trendpick/customerservice/asks/detail.html
  src/main/resources/templates/trendpick/orders/detail.html
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/products/modify.html
  src/main/resources/templates/trendpick/products/register.html
  src/main/resources/templates/trendpick/usr/cart/list.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
Labels: feature

#272 [#271] 상품 옵션에 대한 생성,수정 로직을 수정한다.
  src/main/java/project/trendpick_pro/domain/product/controller/ProductController.java
  src/main/java/project/trendpick_pro/domain/product/entity/dto/ProductRequest.java
  src/main/java/project/trendpick_pro/domain/product/entity/productOption/dto/ProductOptionSaveRequest.java
  src/main/resources/application-data.yml
  src/main/resources/static/resource/common/common.css
  src/main/resources/templates/trendpick/products/list.html
  src/main/resources/templates/trendpick/products/modify.html
  src/main/resources/templates/trendpick/products/register.html
Labels: feature, refactor

#276 [#275] 판매내역 정산금, 상품 상세페이지 UI를 수정한다.
  src/main/resources/templates/trendpick/admin/sales.html
  src/main/resources/templates/trendpick/products/detailpage.html
Labels: feature, refactor

#279 Feat/266_UseCouponCard
  src/main/java/project/trendpick_pro/domain/coupon/controller/CouponCardController.java
  src/main/java/project/trendpick_pro/domain/coupon/controller/CouponController.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/Coupon.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/CouponCard.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/CouponStatus.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/dto/CouponDto.java
  src/main/java/project/trendpick_pro/domain/coupon/entity/dto/response/CouponCardByApplyResponse.java
  src/main/java/project/trendpick_pro/domain/coupon/repository/CouponCardRepository.java
  src/main/java/project/trendpick_pro/domain/coupon/repository/CouponRepository.java
  src/main/java/project/trendpick_pro/domain/coupon/service/CouponCardService.java
  src/main/java/project/trendpick_pro/domain/coupon/service/CouponService.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderDetailResponse.java
  src/main/java/project/trendpick_pro/domain/orders/entity/dto/response/OrderResponse.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderItemRepository.java
  src/main/java/project/trendpick_pro/domain/orders/repository/OrderRepositoryImpl.java
  src/main/java/project/trendpick_pro/domain/product/repository/ProductRepository.java
  src/main/java/project/trendpick_pro/domain/product/service/ProductService.java
  src/main/java/project/trendpick_pro/global/tosspayment/controller/PaymentController.java
  src/main/resources/application-ela.yml
  src/main/resources/templates/trendpick/coupons/couponcards.html
  src/main/resources/templates/trendpick/orders/detail.html
  src/main/resources/templates/trendpick/orders/order-form.html
  src/main/resources/templates/trendpick/products/coupons.html
  src/main/resources/templates/trendpick/products/detailpage.html
  src/main/resources/templates/trendpick/usr/cart/list.html
Labels: feature, refactor

#282 docs: S3로 이미지 경로 변경 (#280)
  build.gradle
  src/main/java/project/trendpick_pro/global/basedata/BaseData.java
Labels: feature

#287 S3 images
  build.gradle
  src/main/java/project/trendpick_pro/domain/common/controller/CommonController.java
  src/main/java/project/trendpick_pro/domain/orders/contoller/OrderController.java
  src/main/java/project/trendpick_pro/domain/orders/entity/Order.java
  src/main/java/project/trendpick_pro/domain/orders/entity/OrderItem.java
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
  src/main/java/project/trendpick_pro/domain/product/entity/product/Product.java
  src/main/java/project/trendpick_pro/global/config/WebSocketConfig.java
  src/main/java/project/trendpick_pro/global/tosspayment/controller/PaymentController.java
  src/main/resources/application-data.yml
  src/main/resources/application.yml
  src/main/resources/templates/trendpick/orders/standByOrder.html
  src/main/resources/templates/trendpick/usr/layout/layout.html
Labels: feature, refactor

#289 refactor: 리스너 메소드 완료시 신호를 전송 (#280)
  src/main/resources/application.yml
Labels: refactor

#302 refactor: paylod 변수형 변경
  src/main/java/project/trendpick_pro/domain/orders/service/OrderService.java
Labels: feature, refactor
